"""Sessions router — /api/sessions/* endpoints.

CRUD + listing + search + summarise. Depends on SessionStore, llm_engine, and
session_id is just the dict key (UUID-shaped strings).

Note: /api/sessions/new intentionally does NOT require a query/body — it just
resets the in-memory sliding window on the engine so the next /api/chat/stream
start a fresh conversation. The session_id is generated by the client.
"""
from __future__ import annotations

import asyncio

from fastapi import APIRouter, Depends, HTTPException, Path as PathParam, Request

from dependencies        import get_llm, get_session_store, require_api_key, get_rate_limiter
from request_models      import RenameRequest, SESSION_ID_PATTERN
from sessions           import SessionStore
from util               import run_sync


router = APIRouter()


@router.post("/api/sessions/new")
async def api_new_session(request: Request,
                           llm=Depends(get_llm),
                           _auth=Depends(require_api_key),
                           limiter=Depends(get_rate_limiter)):
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    """Reset in-memory sliding window only; the client picks the new session_id."""
    llm.reset_window()
    return {"status": "ok"}


@router.get("/api/sessions")
async def api_sessions(request: Request, limit: int = 100,
                       store: SessionStore = Depends(get_session_store),
                       _auth=Depends(require_api_key),
                       limiter=Depends(get_rate_limiter)):
    """Return most recently updated session index records."""
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    return {"sessions": await run_sync(store.list_index, limit=limit)}


@router.get("/api/sessions/search/{query}")
async def api_search_sessions(query: str, request: Request,
                               store: SessionStore = Depends(get_session_store),
                               _auth=Depends(require_api_key),
                               limiter=Depends(get_rate_limiter)):
    """Search session history using in-memory mtime-keyed cache (Group 5).

    Cache is invalidated on save/delete so stale reads don't persist.
    Full FTS is punted per AGENTS.md.
    """
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    return {"query": query, "results": await run_sync(store.search_text, query)}


@router.get("/api/sessions/{sid}")
async def api_get_session(request: Request,
                          sid: str = PathParam(pattern=SESSION_ID_PATTERN),
                          store: SessionStore = Depends(get_session_store),
                          _auth=Depends(require_api_key),
                          limiter=Depends(get_rate_limiter)):
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    return await run_sync(store.load, sid)


@router.delete("/api/sessions/{sid}")
async def api_del_session(request: Request,
                          sid: str = PathParam(pattern=SESSION_ID_PATTERN),
                          store: SessionStore = Depends(get_session_store),
                          _auth=Depends(require_api_key),
                          limiter=Depends(get_rate_limiter)):
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    await run_sync(store.delete, sid)
    return {"status": "ok"}


@router.post("/api/sessions/{sid}/rename")
async def api_rename(req: RenameRequest, request: Request,
                    sid: str = PathParam(pattern=SESSION_ID_PATTERN),
                    store: SessionStore = Depends(get_session_store),
                    _auth=Depends(require_api_key),
                    limiter=Depends(get_rate_limiter)):
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    d = await run_sync(store.load, sid)
    d["title"] = req.title
    await run_sync(store.save, d)
    return {"status": "ok"}


@router.post("/api/sessions/{sid}/summarise")
async def api_summarise(request: Request,
                        sid: str = PathParam(pattern=SESSION_ID_PATTERN),
                        llm=Depends(get_llm), store: SessionStore = Depends(get_session_store),
                        _auth=Depends(require_api_key),
                        limiter=Depends(get_rate_limiter)):
    ip = request.client.host if request.client else "unknown"
    if not limiter.check(ip):
        raise HTTPException(429, "Rate limit exceeded; try again shortly.")
    if not llm.is_loaded():
        raise HTTPException(400, "No model")
    session = await run_sync(store.load, sid)
    msgs = session.get("messages", [])
    if len(msgs) < 4:
        return {"status": "error", "message": "Not enough messages."}
    transcript = "\n".join(
        f"{'User' if m['role'] == 'user' else 'AI'}: {m['content'][:300]}"
        for m in msgs[-30:]
    )
    prompt = f"Summarise this conversation in 3-5 bullet points:\n\n{transcript}"
    loop = asyncio.get_event_loop()
    summary = await loop.run_in_executor(
        None, lambda: "".join(list(llm.stream_tokens([], prompt, "Summarise briefly.", 0.3, 512)))
    )
    return {"status": "ok", "summary": summary.strip()}
